---
services: docker

env:
  # Test package install on all supported OSes.
  - distro: gallium
    playbook: test.yml
  - distro: xenial
    playbook: test.yml

script:
  # Configure test script so we can run extra tests after playbook is run.
  - export container_id=$(date +%s)
  - export cleanup=false
  - export test_suite=false

  # Run tests.
  - chmod +x ${PWD}/tests/run-test.sh
  - ${PWD}/tests/run-test.sh

  # Ensure python is installed and working.
  - 'docker exec --tty ${container_id} env TERM=xterm python -V'
  - 'docker exec --tty ${container_id} env TERM=xterm pip -V'

  # Test whether packages are installed as specified.
  - docker exec --tty ${container_id} pip list installed | grep -e '^ipaddress.*1\.0\.18.*$'
  - docker exec --tty ${container_id} pip list installed | grep '^colorama'

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/